import {evaluate} from './expression.js';
export const formatValue=value=>typeof value==='number'?(Number.isFinite(value)?Number(value.toFixed(4)).toLocaleString('en-US',{maximumFractionDigits:4}):'Nonfinite result'):String(value??'No value returned');
export function caseResult(mission,answer,result,task){
 if(task.codeIndex!==undefined){const check=result.codeChecks?.[task.codeIndex],test=mission.codeCases[task.codeIndex];const actual=check?.actual;return {readouts:[{label:'Your JavaScript output',value:actual,unit:test.throws?'':mission.number===13?'rad':'N m'},{label:'Expected behavior',value:test.throws?'Input rejection':test.expected,unit:test.throws?'':mission.number===13?'rad':'N m'}],inputs:test.input,conclusion:task.travelLimit&&typeof actual==='number'?(Math.abs(actual)<=task.travelLimit?'Within signed travel':'Outside signed travel'):(check?.passed?'Implementation matches case':'Implementation needs revision'),choices:task.travelLimit?['Within signed travel','Outside signed travel']:['Implementation matches case','Implementation needs revision'],note:task.travelLimit?'Local travel only. Operational crosswind evidence remains insufficient.':'These are outputs from your executed function, not supplied simulation values.'};}
 const vars={...mission.variables};for(const f of mission.fields)if(f.type==='number')vars[f.id]=Number(answer[f.id]);Object.assign(vars,task.inputs);
 let student;try{student=evaluate(answer.equation,vars);}catch{}vars.student=student;
 const readouts=task.readouts.map(r=>{let value=r.answerText?answer[r.answerText]:r.text;try{if(r.studentField)value=evaluate(answer[r.studentField],vars);else if(r.studentMargin)value=evaluate(r.capacity,vars)-evaluate(answer[r.studentMargin],vars);else if(r.expression)value=evaluate(r.expression,vars);}catch{value='Unavailable: revise the expression or inputs';}return {...r,value};});
 const c=task.comparison;let pass=false;try{const l=evaluate(c.left,vars),r=evaluate(c.right,vars);pass=c.answerField?answer[c.answerField]===c.expected:c.op==='lte'?l<=r&&(c.min===undefined||l>=c.min):c.op==='eq'?Math.abs(l-r)<1e-6:l>=r;}catch{return {readouts,inputs:task.inputs,conclusion:'Cannot evaluate this case',choices:['Cannot evaluate this case'],note:'Correct the inputs before recording this case.'};}
 const wrongDirection=c.min!==undefined&&evaluate(c.left,vars)<c.min;return {readouts,inputs:task.inputs,conclusion:wrongDirection?c.directionFailure:pass?c.pass:c.fail,choices:[...new Set([c.pass,c.fail,c.directionFailure].filter(Boolean))],note:task.evidenceNote};
}
export function investigationComplete(mission,work){return (mission.investigation?.required||[]).every(id=>{const task=mission.investigation.cases.find(c=>c.id===id),e=work.observations?.[id];if(!e||e.attemptId!==work.attempt?.id||e.note?.trim().length<12)return false;const view=caseResult(mission,work.answer,work.attempt.result,task);return e.conclusion===view.conclusion&&view.conclusion!=='Cannot evaluate this case';});}
export function deliverySnapshot(w){return JSON.stringify({answer:w.answer,attempt:w.attempt?.id,observations:w.observations,reflection:w.reflection});}
