import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,it,expect} from 'vitest';
import fs from 'node:fs';
import Experiment from '../../src/core/onboarding/Experiment.jsx';
import {pitchAngle} from '../../src/core/onboarding/PitchReplay.jsx';
import {caseResult,assessInterpretation,deliverySnapshot} from '../../src/core/onboarding/investigation.js';
import {runMission} from '../../src/core/onboarding/engine.js';
const missions=Array.from({length:13},(_,i)=>JSON.parse(fs.readFileSync(new URL(`../../lessons/onboarding/mission${String(i+1).padStart(2,'0')}.json`,import.meta.url))));
function recordFor(m){const answer=Object.fromEntries(m.fields.map(f=>[f.id,f.type==='number'?0:f.type==='select'?f.options[0]:'A written explanation for review.']));for(const c of m.checks)if(c.field)answer[c.field]=c.expected;if(m.number===2)answer.equation='deltaT*y';if(m.number===13)answer.equation='-(CnBeta*beta+Cn0)/CnRudder';const result=runMission(m,answer);result.codeChecks=m.codeCases?.map(c=>({actual:c.throws?'input rejection':c.expected,passed:true}));return {answer,attempt:{id:'current',result},observations:{}};}
describe('interpretation before feedback',()=>{
 it('does not render an answer banner or case-status verdict before submission in any mission',()=>{for(const m of missions){const record=recordFor(m);for(const task of m.investigation.cases){record.view={caseId:task.id};const html=renderToStaticMarkup(<Experiment mission={m} record={record} stale={false} onChange={()=>{}}/>);expect(html).not.toMatch(/Case conclusion:|Observed comparison:|Deadline met|Deadline missed|capacity: sufficient/);expect(html).not.toMatch(/Your interpretation matches this comparison/);expect(task.label).not.toMatch(/insufficient|reject|demands twice|reverses rudder/i);expect(caseResult(m,record.answer,record.attempt.result,task).choices.length).toBeGreaterThan(1);}}});
 it('requires evidence and a conclusion, retains the answer until the comparison is correct',()=>{const m=missions[0],record=recordFor(m),task=m.investigation.cases[0],view=caseResult(m,record.answer,record.attempt.result,task),draft={conclusion:'Insufficient authority',evidence:'0.6505',note:'The result is below the specified minimum.'};const wrong=assessInterpretation(m,record.answer,record.attempt.result,task,draft);expect(wrong.correct).toBe(false);expect(wrong.feedback).not.toContain('Requirement met');draft.conclusion=view.conclusion;draft.evidence='9';expect(assessInterpretation(m,record.answer,record.attempt.result,task,draft).correct).toBe(false);draft.evidence='0.6505';expect(assessInterpretation(m,record.answer,record.attempt.result,task,draft).correct).toBe(true);});
 it('accepts readable evidence precision across all case readouts',()=>{for(const m of missions){const record=recordFor(m);for(const task of m.investigation.cases){const v=caseResult(m,record.answer,record.attempt.result,task),value=v.readouts[task.evidenceIndex||0].value;expect(assessInterpretation(m,record.answer,record.attempt.result,task,{conclusion:v.conclusion,evidence:typeof value==='number'?value.toFixed(4):value,note:'Compared this quantity with the stated criterion.'}).correct,m.id+':'+task.id).toBe(true);}}});
 it('includes changed interpretation attempts in checkpoint freshness',()=>{const w={answer:{},attempt:{id:'a'},interpretations:{}};const before=deliverySnapshot(w);w.interpretations.x=[{correct:false}];expect(deliverySnapshot(w)).not.toBe(before);});
});
describe('bounded pitch replay',()=>{
 it('uses physical time, independent of playback speed, and the constant-initial-acceleration relation',()=>{expect(pitchAngle(.12,0)).toBe(0);expect(pitchAngle(.12,.5)).toBeCloseTo(.8594367,6);expect(pitchAngle(.12,.5)/pitchAngle(.12,.25)).toBeCloseTo(4);});
 it('shows all three speed curves and a time scrubber without extending the physical interval',()=>{const m=missions[0],record=recordFor(m),html=renderToStaticMarkup(<Experiment mission={m} record={record} stale={false} onChange={()=>{}}/>);expect(html).toContain('Pitch angle versus simulated time');expect(html).toContain('5 seconds to watch');expect(html).toContain('max="0.5"');for(const c of m.investigation.cases)expect(html).toContain(c.label);expect(html).toContain('not a takeoff trajectory');});
});
